#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 26 23:19:25 EDT 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b0fc678e9c8e4202931ffcc24be16b0b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot halfAdder_behav xil_defaultlib.halfAdder -log elaborate.log"
xelab -wto b0fc678e9c8e4202931ffcc24be16b0b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot halfAdder_behav xil_defaultlib.halfAdder -log elaborate.log

